## File for Adding assay information from ChEMBL for the SEA Algorithm generated by the Keiser Lab
## The following algorithm inputs all of the assay information extracted from ChEMBL using the following SQL query:
## select td.chembl_id as 'target_chembl_id', md.chembl_id as 'cmpd_chembl_id', act.standard_units, act.standard_value, act.standard_relation, act.doc_id, assays.src_id, assays.confidence_score, assays.curated_by from activities as act join assays on act.assay_id = assays.assay_id join molecule_dictionary as md on act.molregno = md.molregno join target_dictionary as td on assays.tid = td.tid where target_dictionary.organism = 'Homo sapiens' and target_dictionary.target_type = 'SINGLE PROTEIN';
from neo4j.v1 import basic_auth, GraphDatabase
import csv
import time

driver = GraphDatabase.driver("bolt://msgap1.ucsf.edu/:7687", auth=basic_auth("username", "password"))
session = driver.session()

# Return all the Compound_chemblid and Protein_chemblid tuples
record = session.run("MATCH (c:Compound)-[r:INTERACTS_CiP]-(p:Protein) RETURN c.chembl_id as cmpd, p.chembl_id as prot")
cp_arr = []
for rec in record:
    element = str(rec["cmpd"]) + "-" + str(rec["prot"]) # Store tuples in an array
    cp_arr.append(element)

# Name of Property Key --> ic50_values_chembl
# Boolean for Drug_Interaction --> False (drug_interaction: "False") -- Already existing drug_interactions pulled from ChEMBL and DrugBank are set to true

# Name of property key typically looks like: nameoftest_values_chembl. For instance ic50 vals would look like: ic50_values_chembl
# Values are added as arrays, with the bounding relation and the value (to the -log10 of the original value in M) split by a semicolon
# For instance: [4.5665;<. 5.4454;=]

def create_prop_key(param):
    p1 = param.replace(" ", "")
    p2 = p1.lower()
    return p2

count_tot = 0
i = open("parsed_outfile_2.csv", "r")
dict_fin = {}
for line in i:
    cols = line.split(",")
    if line:
        count_tot = count_tot + 1
        split_id = cols[0].split("-")
        tar_id = split_id[0].strip()
        cmpd_id = split_id[1].strip()
        test_init = split_id[2].strip()
        test = create_prop_key(test_init) + "_values_chembl" # Creating the name of the property key

        if (count_tot%1000 == 0):
            print "Count Completed : " + str(count_tot)
        split_val = cols[1].split(";")
        arr_val = []
        for item in split_val:
            item_arr = item.split("|")
            element = item_arr[3].strip() + ";" + item_arr[2].strip()
            arr_val.append(element)
        
        uid_a = cmpd_id + "-"+ tar_id

        if uid_a in cp_arr: # In case the cmpd-prot tuple already exists as a relationship, add that information to the existing relationship
            session.run("MATCH (c:Compound)-[r:INTERACTS_CiP]-(p:Protein) where c.chembl_id = '" + cmpd_id + "' and p.chembl_id = '" + tar_id + "' SET r." + test + " = " + str(arr_val))
            print "Present and Detected!", ("MATCH (c:Compound)-[r:INTERACTS_CiP]-(p:Protein) where c.chembl_id = '" + cmpd_id + "' and p.chembl_id = '" + tar_id + "' SET r." + test + " = " + str(arr_val))
        else:
            su = "false"
            cp_arr.append(uid_a)
            rec_2 = session.run("MATCH (c:Compound)-[r:INTERACTS_CiP]-(p:Protein) where c.chembl_id = '" + cmpd_id + "' and p.chembl_id = '" + tar_id + "' RETURN r.action_type as act")
            for elem in rec_2:
                su = "true"
                print "Got Here!"

            if (su == "true"):
                print "Found Rel, Previously Added", ("MATCH (c:Compound)-[r:INTERACTS_CiP]-(p:Protein) where c.chembl_id = '" + cmpd_id + "' and p.chembl_id = '" + tar_id + "' SET r." + test + " = " + str(arr_val))
                session.run("MATCH (c:Compound)-[r:INTERACTS_CiP]-(p:Protein) where c.chembl_id = '" + cmpd_id + "' and p.chembl_id = '" + tar_id + "' SET r." + test + " = " + str(arr_val))
            else:
                print "New Rel to be added", ("MATCH (c:Compound), (p:Protein) where c.chembl_id = '" + cmpd_id + "' and p.chembl_id = '" + tar_id + "' CREATE (c)-[r:INTERACTS_CiP]->(p) SET r." + test + " = " + str(arr_val) + ", r.action_type = 'UNKNOWN', r.drug_interaction = 'false', r.source = 'ChEMBL', r.license = 'CC BY-SA 3.0'") 
                session.run("MATCH (c:Compound), (p:Protein) where c.chembl_id = '" + cmpd_id + "' and p.chembl_id = '" + tar_id + "' CREATE (c)-[r:INTERACTS_CiP]->(p) SET r." + test + " = " + str(arr_val) + ", r.action_type = 'UNKNOWN', r.drug_interaction = 'false', r.source = 'ChEMBL', r.license = 'CC BY-SA 3.0'")
         
session.close()
        
